# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "opscode-ubuntu-14.04"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"
  config.vm.network "private_network", ip:"10.0.0.2"
  config.vm.synced_folder "../share", "/share"
  config.omnibus.chef_version = :latest
  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "mysql::server"
    chef.json = {
      :mysql => {
          server_root_password: "password",
          server_repl_password: "password",
          server_debian_password: "password",
          version: '5.6',
          port: '3307',
          data_dir: '/data-mysql',
          allow_remote_root: true,
          remove_anonymous_Users: true,
          remove_test_database: true
      }
   }
   end
end

